# Generated by Django 3.1.5 on 2021-01-19 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_user_affiliation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='designeruser',
            name='id',
        ),
        migrations.AddField(
            model_name='businessuser',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designeruser',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
