# Generated by Django 3.1.5 on 2021-01-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_auto_20210120_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_activated',
            field=models.BooleanField(default=False, verbose_name='email verified?'),
        ),
    ]
