# Generated by Django 3.1.5 on 2021-01-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_user_is_email_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='is_business_complete',
            field=models.BooleanField(default=False, verbose_name='business registration complete'),
        ),
        migrations.AddField(
            model_name='designeruser',
            name='is_designer_complete',
            field=models.BooleanField(default=False, verbose_name='designer registration complete'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_activated',
            field=models.BooleanField(default=False, verbose_name='email verified'),
        ),
    ]
