# Generated by Django 3.1.5 on 2021-01-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_auto_20210124_1457'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Project',
        ),
    ]
